services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      DOCKER_MYSQL_PORT: ${DOCKER_MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/local-dump.sql:/docker-entrypoint-initdb.d/local-dump.sql
    ports:
      - ${DOCKER_MYSQL_PORT_FORWARD}:${DOCKER_MYSQL_PORT}
    expose:
      - ${DOCKER_MYSQL_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "${DOCKER_MYSQL_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 5

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - .env
    ports:
      - ${DOCKER_DJANGO_PORT_FORWARD}:${DOCKER_DJANGO_PORT}
      - ${DOCKER_DEBUGGER_PORT_FORWARD}:${DOCKER_DEBUGGER_PORT}
    volumes:
      - .:/sisoc/
    user: "${RUN_UID:-1000}:${RUN_GID:-1000}"
    restart: always

volumes:
  mysql_data:
