name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Setup PIP Cache
      uses: actions/cache@v2
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

    - name: Set up locale
      run: |
        sudo apt-get install -y locales
        sudo locale-gen es_AR.UTF-8
        sudo update-locale LANG=es_AR.UTF-8 LC_ALL=es_AR.UTF-8
        export LC_ALL="es_AR.UTF-8"
        
    - name: Print current directory
      run: | 
        pwd
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv lock --keep-outdated --requirements --dev > requirements.txt
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test
